### ISSUE TITLE
TextInput Label Overlap

### ISSUE THREAD

**Issue by merklegroot** [yamankatby/react-native-material#32]
When a TextInput's value has been set before the user has changed it, the label does not shrink and the text overlaps.
As soon as the user changes the value, the label shrinks as expected.

You can see the issue in the snack below.
<https://snack.expo.dev/Kf980pU2X>

``` typescript
import React, { useState } from 'react';
import { TextInput } from '@react-native-material/core';

const App = () => {
  const [val, setVal] = useState('initial value');
  return (
    <TextInput label="Label" value={val} onChangeText={setVal} />
  );
};

export default App;;
```

![image](https://user-images.githubusercontent.com/40680812/155148473-b802a5e7-e5ef-411b-b6fd-eb8ee6b99d17.png)

**Comment by yamankatby** [comment]
Hi @merklegroot,
Thank you for reporting this issue. Your description is very clear. I will be working on it and I will notify you once this is done.

**Comment by alexghi** [comment]
I still experience this issue, what can be done? 
iOS 16.1
@react-native-material/core: 1.3.7
react: 17.0.1,
react-native: 0.64.1

<img width="160" alt="image" src="https://user-images.githubusercontent.com/11394898/198227165-6d3a521c-65c5-4177-849c-c2be577a6486.png">
