### ISSUE TITLE
BUG: Crash when using pressEffect='ripple'

### ISSUE THREAD

**Issue by sk185701** [yamankatby/react-native-material#36]
It seems as though it's possible for the Pressable onPressOut function to be called before the setRipples in onPressIn takes effect, which results in the ripples array to empty and thus an attempt at animating an undefined value.

Associated log: `ERROR  TypeError: undefined is not an object (evaluating 'ripples[ripples.length - 1].style')`

**Comment by yamankatby** [comment]
Hi @sk185701,

Thank you for reporting this issue and for the PR. Hopefully, I'll find time to merge it this week.
