### ISSUE TITLE
VStack doesn't add spacing if a component is a custom functional component

### ISSUE THREAD

**Issue by Pika-Pool** [yamankatby/react-native-material#39]
See example: https://codesandbox.io/s/frosty-http-1scdrm?file=/src/App.js

In the above example, there is no space after `<Link />` in the rendered result.
But if the same content in `Link` is rendered as it is, the space is added.

I'm not sure if this is a bug or if this is the way its supposed to be.

```js
import React from "react";
import { Text, View } from "react-native";
import { VStack } from "@react-native-material/core";

function Link() {
  return (
    <>
      <Text>Link</Text>
      <Text>Link</Text>
    </>
  );
}

function App() {
  return (
    <VStack spacing={25}>
      <View>
        <Text>Hello</Text>
      </View>
      <View>
        <Text>Hello</Text>
      </View>

      <Link />
      {/* uncommnent the following and comment the prev line */}

      {/* <Text>Link</Text>
      <Text>Link</Text> */}

      <View>
        <Text>Hello</Text>
      </View>
    </VStack>
  );
}

export default App;
```

**Comment by yamankatby** [comment]
Hi @Pika-Pool,
Thank you for reporting this problem, doesn't seem to be an issue, try to add `shouldWrapChildren={true}` to the stack and it suppose to do the trick.

I'll close this issue now, please feel free to reopen it if it doesn't work.
