### ISSUE TITLE
TextInput - Label overlapps input when focusing out

### ISSUE THREAD

**Issue by mikemangas** [yamankatby/react-native-material#50]
I have the problem, that whenever i type into the textinput field (outlined), it works well - the label goes above the text (screenshot 1).
But whenever i focus out, to another input-field, the label goes to its initial place (screenshot 2). I guess it has to do, that the textinput field does not know, that it has a value - but i am not sure how to fix that.
I used the same code the documentations providing (here: https://www.react-native-material.com/docs/components/text-input)

tested on: IOS Simulator, Android Simulator and Poco X2 phone - with the newest react native version and newest react-native-material version.
 
<img width="458" alt="Screenshot 2022-11-21 at 22 51 32" src="https://user-images.githubusercontent.com/85886271/203156034-6e1301dc-0c6e-4153-9611-f9808a1f578c.png">
<img width="458" alt="Screenshot 2022-11-21 at 22 51 42" src="https://user-images.githubusercontent.com/85886271/203156040-3bccc7b2-c29e-4717-929e-e5599803ccd3.png">

**Comment by mikemangas** [comment]
solved: as in the description explained, the value of my textinput was missing... and that was the problem.

**Comment by yamankatby** [comment]
Hey @mikemangas,
Thank you for considering giving feedback 🤩 and closing this issue
